-- --------------------------------------------------------
-- Host:                         localhost
-- Versión del servidor:         5.7.19 - MySQL Community Server (GPL)
-- SO del servidor:              Win64
-- HeidiSQL Versión:             9.4.0.5125
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;


-- Volcando estructura de base de datos para gym
CREATE DATABASE IF NOT EXISTS `gym` /*!40100 DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish_ci */;
USE `gym`;

-- Volcando estructura para tabla gym.ejercicios
CREATE TABLE IF NOT EXISTS `ejercicios` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `id_grupo` int(10) unsigned NOT NULL,
  `ejercicio` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `imagen` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `explicacion` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `tiempo` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `material` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `posicion` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `consejo` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `ejercicios_id_grupo_foreign` (`id_grupo`),
  CONSTRAINT `ejercicios_id_grupo_foreign` FOREIGN KEY (`id_grupo`) REFERENCES `grupos` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=219 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla gym.ejercicios: ~155 rows (aproximadamente)
/*!40000 ALTER TABLE `ejercicios` DISABLE KEYS */;
INSERT INTO `ejercicios` (`id`, `id_grupo`, `ejercicio`, `imagen`, `explicacion`, `tiempo`, `material`, `posicion`, `consejo`, `created_at`, `updated_at`) VALUES
	(57, 1, 'abdominales banco multipower', 'abdominales/abdominales_banco_multipower.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(58, 1, 'abdominales como flexiones', 'abdominales/abdominales_como_flexiones.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(59, 1, 'abdominales con banco', 'abdominales/abdominales_con_banco.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(60, 1, 'abdominales con remo', 'abdominales/abdominales_con_remo.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(61, 1, 'abdominales cuadriceps', 'abdominales/abdominales_cuadriceps.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(62, 1, 'abdominales inferiro', 'abdominales/abdominales_inferiro.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(63, 1, 'abdominales maquina', 'abdominales/abdominales_maquina.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(64, 1, 'abdominales pies elebados', 'abdominales/abdominales_pies_elebados.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(65, 1, 'abdominales polea', 'abdominales/abdominales_polea.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(66, 1, 'abdominales polea triceps', 'abdominales/abdominales_polea_triceps.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(67, 1, 'abdominales superior', 'abdominales/abdominales_superior.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(68, 1, 'oblicuos', 'abdominales/oblicuos.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(69, 1, 'oblicuos pres banca', 'abdominales/oblicuos_pres_banca.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(70, 1, 'oblicuos tradicional', 'abdominales/oblicuos_tradicional.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(71, 2, 'curl biceps', 'biceps/curl_biceps.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(72, 2, 'curl biceps aberto', 'biceps/curl_biceps_aberto.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(73, 2, 'curl biceps maquina', 'biceps/curl_biceps_maquina.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(74, 2, 'curl biceps polea', 'biceps/curl_biceps_polea.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(75, 2, 'curl concentrado', 'biceps/curl_concentrado.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(76, 2, 'curl concentrado cerrado', 'biceps/curl_concentrado_cerrado.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(77, 2, 'curl concentrado depie', 'biceps/curl_concentrado_depie.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(78, 2, 'curl concentrado maquina', 'biceps/curl_concentrado_maquina.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(80, 2, 'curl concentrado multiPower abierto', 'biceps/curl_concentrado_multiPower_abierto.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(81, 2, 'curl concentrado rodila', 'biceps/curl_concentrado_rodila.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(82, 2, 'curl con mancuernas', 'biceps/curl_con_mancuernas.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(83, 2, 'curl con polea', 'biceps/curl_con_polea.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(84, 2, 'curl con polea barra recta', 'biceps/curl_con_polea_barra_recta.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(85, 2, 'curl estiramiento', 'biceps/curl_estiramiento.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(86, 2, 'curl martillo', 'biceps/curl_martillo.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(87, 2, 'curl martillo depie', 'biceps/curl_martillo_depie.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(88, 3, 'triceps concentrado maquina', 'triceps/triceps_concentrado_maquina.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(89, 3, 'triceps concentrado maquina barra v', 'triceps/triceps_concentrado_maquina_barra_v.jpg', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(90, 3, 'triceps concentrado maquina un brazo', 'triceps/triceps_concentrado_maquina_un_brazo.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(91, 3, 'triceps fondos entre bancos', 'triceps/triceps_fondos_entre_bancos.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(92, 3, 'triceps fondos maquina', 'triceps/triceps_fondos_maquina.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(93, 3, 'triceps pajaritos', 'triceps/triceps_pajaritos.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(94, 3, 'triceps pajaritos un brazo', 'triceps/triceps_pajaritos_un_brazo.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(95, 3, 'triceps presbanca', 'triceps/triceps_presbanca.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(96, 3, 'triceps presbanca dos mancuernas', 'triceps/triceps_presbanca_dos_mancuernas.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(97, 3, 'triceps presbanca multipower', 'triceps/triceps_presbanca_multipower.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(98, 3, 'triceps sentado dos brazos una mancuerna', 'triceps/triceps_sentado_dos_brazos_una_mancuerna.jpg', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(99, 3, 'triceps sentado un brazos una mancuerna', 'triceps/triceps_sentado_un_brazos_una_mancuerna.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(100, 4, 'espalda banco', 'espalda/espalda_banco.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(101, 4, 'espalda barra multipower', 'espalda/espalda_barra_multipower.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(102, 4, 'espalda biceps polea', 'espalda/espalda_biceps_polea.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(103, 4, 'espalda discos', 'espalda/espalda_discos.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(104, 4, 'espalda dominadas', 'espalda/espalda_dominadas.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(105, 4, 'espalda dominadas maquina', 'espalda/espalda_dominadas_maquina.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(106, 4, 'espalda exterior barra multipower', 'espalda/espalda_exterior_barra_multipower.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(107, 4, 'espalda mancuernas', 'espalda/espalda_mancuernas.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(108, 4, 'espalda polea brazos estirados', 'espalda/espalda_polea_brazos_estirados.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(109, 4, 'espalda polea delante', 'espalda/espalda_polea_delante.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(110, 4, 'espalda polea detras', 'espalda/espalda_polea_detras.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(111, 4, 'espalda remo cerrado', 'espalda/espalda_remo_cerrado.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(112, 5, 'Hombro', 'hombros/Hombro.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(113, 5, 'Hombro aperturas', 'hombros/Hombro_aperturas.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(114, 5, 'Hombro aperturas banco lateral', 'hombros/Hombro_aperturas_banco_lateral.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(115, 5, 'Hombro aperturas inclinado', 'hombros/Hombro_aperturas_inclinado.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(116, 5, 'Hombro aperturas polea', 'hombros/Hombro_aperturas_polea.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(117, 5, 'Hombro deltoides', 'hombros/Hombro_deltoides.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(118, 5, 'Hombro deltoides mancuernas', 'hombros/Hombro_deltoides_mancuernas.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(119, 5, 'Hombro deltoides maquina', 'hombros/Hombro_deltoides_maquina.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(120, 5, 'Hombro elebaciones', 'hombros/Hombro_elebaciones.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(121, 5, 'Hombro elebaciones polea', 'hombros/Hombro_elebaciones_polea.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(122, 5, 'Hombro elebaciones una a una', 'hombros/Hombro_elebaciones_una_a_una.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(123, 5, 'Hombro pajaritos', 'hombros/Hombro_pajaritos.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(124, 5, 'Hombro', 'hombros/Hombro.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(125, 5, 'Hombro aperturas', 'hombros/Hombro_aperturas.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(126, 5, 'Hombro aperturas banco lateral', 'hombros/Hombro_aperturas_banco_lateral.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(127, 5, 'Hombro aperturas inclinado', 'hombros/Hombro_aperturas_inclinado.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(128, 5, 'Hombro aperturas polea', 'hombros/Hombro_aperturas_polea.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(129, 5, 'Hombro deltoides', 'hombros/Hombro_deltoides.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(130, 5, 'Hombro deltoides mancuernas', 'hombros/Hombro_deltoides_mancuernas.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(131, 5, 'Hombro deltoides maquina', 'hombros/Hombro_deltoides_maquina.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(132, 5, 'Hombro elebaciones', 'hombros/Hombro_elebaciones.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(133, 5, 'Hombro elebaciones polea', 'hombros/Hombro_elebaciones_polea.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(134, 5, 'Hombro elebaciones una a una', 'hombros/Hombro_elebaciones_una_a_una.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(135, 5, 'Hombro pajaritos', 'hombros/Hombro_pajaritos.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(136, 6, 'pecho aperturas', 'pecho/pecho_aperturas.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(137, 6, 'pecho aperturas mancuernas', 'pecho/pecho_aperturas_mancuernas.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(138, 6, 'pecho aperturas maquina', 'pecho/pecho_aperturas_maquina.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(139, 6, 'pecho aperturas poleas', 'pecho/pecho_aperturas_poleas.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(140, 6, 'pecho concentrado', 'pecho/pecho_concentrado.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(141, 6, 'pecho dominadas', 'pecho/pecho_dominadas.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(142, 6, 'pecho flexiones', 'pecho/pecho_flexiones.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(143, 6, 'pecho inclinado mancuernas', 'pecho/pecho_inclinado_mancuernas.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(144, 6, 'pecho inclinado polea', 'pecho/pecho_inclinado_polea.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(145, 6, 'pecho maquina', 'pecho/pecho_maquina.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(146, 6, 'pecho maquina concentrado', 'pecho/pecho_maquina_concentrado.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(147, 6, 'pecho pesolibre', 'pecho/pecho_pesolibre.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(148, 6, 'pecho peso frances', 'pecho/pecho_peso_frances.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(149, 6, 'pecho poleas', 'pecho/pecho_poleas.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(150, 6, 'pecho presbanca', 'pecho/pecho_presbanca.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(151, 6, 'pecho presbanca inclinado mancuernas', 'pecho/pecho_presbanca_inclinado_mancuernas.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(152, 6, 'pecho presbanca_mancuernas', 'pecho/pecho_presbanca_mancuernas.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(153, 6, 'pecho pres banca inclinado', 'pecho/pecho_pres_banca_inclinado.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(154, 6, 'presbanca', 'pecho/presbanca.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(155, 7, 'Cuadriceps', 'piernas/Cuadriceps.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(156, 7, 'Cuadriceps manuernas', 'piernas/Cuadriceps_manuernas.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(157, 7, 'Cuadriceps Prensa', 'piernas/Cuadriceps_Prensa.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(158, 7, 'Cuadriceps Prensa 2', 'piernas/Cuadriceps_Prensa_2.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(159, 7, 'cuadriceps pullover', 'piernas/cuadriceps_pullover.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(160, 7, 'cuadriceps sentadillas', 'piernas/cuadriceps_sentadillas.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(161, 7, 'gemelos escalon', 'piernas/gemelos_escalon.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(162, 7, 'gemelos escalon sentado', 'piernas/gemelos_escalon_sentado.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(163, 7, 'gemelos prensa', 'piernas/gemelos_prensa.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(169, 8, 'bicycle crunch', 'sinpesas_abdominal/bicycle_crunch.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(170, 8, 'crunch', 'sinpesas_abdominal/crunch.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(171, 8, 'diagona plank', 'sinpesas_abdominal/diagona_plank.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(172, 8, 'kneli side plank', 'sinpesas_abdominal/kneli_side_plank.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(173, 8, 'plank', 'sinpesas_abdominal/plank.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(174, 8, 'reverse crunch', 'sinpesas_abdominal/reverse_crunch.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(175, 8, 'side plank', 'sinpesas_abdominal/side_plank.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(176, 8, 'side plank reach', 'sinpesas_abdominal/side_plank_reach.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(177, 8, 'sit up', 'sinpesas_abdominal/sit_up.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(179, 9, 'horcestance', 'sinpesas_espalda/horcestance.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(180, 9, 'superman', 'sinpesas_espalda/superman.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(181, 9, 'wraise', 'sinpesas_espalda/wraise.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(182, 9, 'yraise', 'sinpesas_espalda/yraise.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(183, 10, 'box jump', 'sinpesas_piernas_y_gluteos/box_jump.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(184, 10, 'but bridge', 'sinpesas_piernas_y_gluteos/but_bridge.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(185, 10, 'lunge', 'sinpesas_piernas_y_gluteos/lunge.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(186, 10, 'one led rdl', 'sinpesas_piernas_y_gluteos/one_led_rdl.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(187, 10, 'side hip abduct', 'sinpesas_piernas_y_gluteos/side_hip_abduct.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(188, 10, 'side lunge', 'sinpesas_piernas_y_gluteos/side_lunge.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(189, 10, 'side skate jump', 'sinpesas_piernas_y_gluteos/side_skate_jump.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(190, 10, 'squat', 'sinpesas_piernas_y_gluteos/squat.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(191, 10, 'step up', 'sinpesas_piernas_y_gluteos/step_up.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(192, 10, 'wall sit', 'sinpesas_piernas_y_gluteos/wall_sit.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(193, 11, 'High knees', 'sinpesas_todo_el_cuerpo/High_knees.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(194, 11, 'inchworm', 'sinpesas_todo_el_cuerpo/inchworm.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(195, 11, 'jumping jack', 'sinpesas_todo_el_cuerpo/jumping_jack.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(196, 11, 'jump rope', 'sinpesas_todo_el_cuerpo/jump_rope.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(197, 11, 'squat jump', 'sinpesas_todo_el_cuerpo/squat_jump.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(198, 12, 'chin up', 'sinpesas_tronco/chin_up.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(199, 12, 'dip', 'sinpesas_tronco/dip.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(200, 12, 'pushup', 'sinpesas_tronco/pushup.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(201, 12, 'wallpush', 'sinpesas_tronco/wallpush.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(202, 12, 'wallslide', 'sinpesas_tronco/wallslide.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(203, 12, 'chin_up', 'sinpesas_tronco/chin_up.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(204, 12, 'dip', 'sinpesas_tronco/dip.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(205, 12, 'pushup', 'sinpesas_tronco/pushup.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(206, 12, 'wallpush', 'sinpesas_tronco/wallpush.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(207, 12, 'wallslide', 'sinpesas_tronco/wallslide.png', 'Haz rotaciones de pelvis hacia un lado y luego hacia otro, manten siempre la posicion de los hombros', '00:05 m', 'sin material', 'ponte de pie en la placa giratoria que las mÃ¡quinas dedicadas a este ejercicio tienen. Las manos en los agarres.', 'Flexiona un poco las rodillas para evitar tirones y controlar las rotaciones, Si quieres intensificar el esfuerzo sobre los oblicuos, flexiona ligeramente la espalda', NULL, NULL),
	(208, 13, 'Hombros y espalda', 'estiramientos/hombro_espalda.png', 'Ponte derecho y estira los brazos hacia arriba.', '30 seg', 'sin material', 'De pie y con las manos estiradas.', 'No fuerces el estiramiento de los brazos hacia arriba,parate cuando notes que los hombros estan al limite. No arquees la espalda ni el cuello, mira hacia un punto fijo.', '2005-06-17 18:00:00', NULL),
	(209, 13, 'Músculos isquiotibiales', 'estiramientos/musculos_isquiotibiales.png', 'Agachate sin flexionar las rodilla y manten la espalda recta.', '30 seg', 'sin material', '.', 'No dobles las piernas durante el ejercicio para mantener la eficacia.No dobles el torso, mantenlo siempre recto', NULL, NULL),
	(210, 13, 'Músculos isquiotibiales 2', 'estiramientos/musculos_isquiotibiales2.png', 'Agachate sin flexionar las rodillas, estira tus brazos 30 seg hacia un lado de tu pie y los otro 30 hacia el otro.', '60 seg', 'sin material', '.', 'No dobles las piernas durante el ejercicio para mantener la eficacia.', NULL, NULL),
	(211, 13, 'Aductores', 'estiramientos/aductores.png', '.', '60 seg', 'sin material', '.', 'No dobles el torso, mantenlo paralelo al suelo.No excedas la punta del pie con la rodilla para no crear problemas con las articulaciones.', NULL, NULL),
	(212, 13, 'Cuadriceps', 'estiramientos/cuadriceps.png', '.', '60 seg', 'sin material', '.', 'La rodilla de la pierna trasera no debe tocar el suelo durante el ejercicio.\r\nLa pierna trasera debe estar extendida para estirar el cuadriceps.', NULL, NULL),
	(213, 13, 'Hombros', 'estiramientos/hombros.png', '.', '60 seg', 'sin material', '.', 'No tires del brazo demasiado rapido, ejecuta un movimiento fluido.\r\nNo apliques una fuerza execiva en el hombro, para cuando sientas dolor.', NULL, NULL),
	(214, 13, 'Pectorales', 'estiramientos/pectorales.png', 'Ponte de pie y estaria las manos hacia atras.', '30 seg', 'sin material', '.', 'No fuerces el movimiento hacia arriba, para cuando notes que hayas llegado al limite.\r\n Realiza un movimiento lento y regular o puedes tener problema en las articulaciones.', NULL, NULL),
	(215, 13, 'Cervicales', 'estiramientos/cervicales.png', 'Ponte de pie y estira el el cuello 30 segundos hacia un lado y luego hacia el otro.', '60 seg', 'sin material', '.', 'No levantes los hombros, mantenlos relajados durante el ejercicio.\r\nPara lograrlo mira hacia un punto fijo.', NULL, NULL),
	(216, 13, 'Cervical 2 ', 'estiramientos/cervicales2.png', 'Estira el cuello haciendo movimiento giratorios', '60 seg ', 'sin material', '.', 'Manten la espalda recta durante todo el ejercicio.\r\nNo levantes los hombros, es importante que se mantengan bajos y relajados.', NULL, NULL),
	(217, 13, 'Hombros aducidos', 'estiramientos/hombros2.png', 'Extiende los brazos hacia los lados y hacia adelante.', '30 seg', 'sin material', '.', 'No dobles ni arquees la espalda, manten el abdomen contraido para estabilizar la columna y evitar lesiones.', NULL, NULL),
	(218, 13, 'Rotacion de brazos', 'estiramientos/rotacion_brazos.png', 'Estira los brazos hacia los lados y haz movimientos giratorios.\r\nSi no puedes hacerlo pon tus manos sobre el hombro.', '30 seg', 'sin material', '.', 'No levantes los hombros, mantenlos bajos y relajados.No dobles los brazos, mantenlos siempre estirados.\r\nNo dobles la cabeza mantela siempre en linea con la espalda.', NULL, NULL);
/*!40000 ALTER TABLE `ejercicios` ENABLE KEYS */;

-- Volcando estructura para tabla gym.ejercicio_modalidad
CREATE TABLE IF NOT EXISTS `ejercicio_modalidad` (
  `id_ejercicio` int(10) unsigned NOT NULL,
  `id_modalidad` int(10) unsigned NOT NULL,
  PRIMARY KEY (`id_ejercicio`,`id_modalidad`),
  KEY `ejercicio_modalidad_id_modalidad_foreign` (`id_modalidad`),
  CONSTRAINT `ejercicio_modalidad_id_ejercicio_foreign` FOREIGN KEY (`id_ejercicio`) REFERENCES `ejercicios` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `ejercicio_modalidad_id_modalidad_foreign` FOREIGN KEY (`id_modalidad`) REFERENCES `modalidads` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla gym.ejercicio_modalidad: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `ejercicio_modalidad` DISABLE KEYS */;
/*!40000 ALTER TABLE `ejercicio_modalidad` ENABLE KEYS */;

-- Volcando estructura para tabla gym.entrenos
CREATE TABLE IF NOT EXISTS `entrenos` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `id_modalidad` int(10) unsigned NOT NULL,
  `repeticiones` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `serie` int(11) NOT NULL,
  `nivel` int(11) NOT NULL,
  `peso` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `entrenos_id_modalidad_foreign` (`id_modalidad`),
  CONSTRAINT `entrenos_id_modalidad_foreign` FOREIGN KEY (`id_modalidad`) REFERENCES `modalidads` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla gym.entrenos: ~15 rows (aproximadamente)
/*!40000 ALTER TABLE `entrenos` DISABLE KEYS */;
INSERT INTO `entrenos` (`id`, `id_modalidad`, `repeticiones`, `serie`, `nivel`, `peso`, `created_at`, `updated_at`) VALUES
	(1, 1, '12-20', 4, 1, '12-100', NULL, NULL),
	(2, 1, '12-20', 3, 2, '6-12 ', NULL, NULL),
	(3, 1, '12-20', 2, 3, '3-6', NULL, NULL),
	(4, 2, '10-12', 4, 1, '12-100', NULL, NULL),
	(5, 2, '10-12', 3, 2, '6-12 ', NULL, NULL),
	(6, 2, '10-12', 2, 3, '3-6', NULL, NULL),
	(7, 3, '8-10', 4, 1, '12-100', NULL, NULL),
	(8, 3, '8-10', 3, 2, '6-12 ', NULL, NULL),
	(9, 3, '8-10', 2, 3, '3-6', NULL, NULL),
	(10, 4, '13-15', 4, 1, '12-100', NULL, NULL),
	(11, 4, '13-15', 3, 2, '6-12 ', NULL, NULL),
	(12, 4, '13-15', 2, 3, '3-6', NULL, NULL),
	(13, 5, '3 aguantando', 1, 1, '0', NULL, NULL),
	(14, 5, '3 aguantando', 1, 2, '0', NULL, NULL),
	(15, 5, '3 aguantando', 1, 3, '0', NULL, NULL);
/*!40000 ALTER TABLE `entrenos` ENABLE KEYS */;

-- Volcando estructura para tabla gym.grupos
CREATE TABLE IF NOT EXISTS `grupos` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `grupo` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla gym.grupos: ~13 rows (aproximadamente)
/*!40000 ALTER TABLE `grupos` DISABLE KEYS */;
INSERT INTO `grupos` (`id`, `grupo`, `created_at`, `updated_at`) VALUES
	(1, 'abdominales', '2018-05-23 17:32:22', '2018-05-23 17:32:22'),
	(2, 'bíceps', '2018-05-23 17:32:46', '2018-05-23 17:32:46'),
	(3, 'tríceps', '2018-05-23 17:33:30', '2018-05-23 17:33:30'),
	(4, 'espalda', '2018-05-23 17:33:48', '2018-05-23 17:33:48'),
	(5, 'hombro', '2018-05-23 17:34:02', '2018-05-23 17:34:02'),
	(6, 'pecho', '2018-05-23 17:34:15', '2018-05-23 17:34:15'),
	(7, 'piernas', '2018-05-23 17:34:23', '2018-05-23 17:34:24'),
	(8, 'sin pesas abdominal', '2018-05-23 17:35:03', '2018-05-23 17:35:03'),
	(9, 'sin pesas espalda', '2018-05-23 17:35:11', '2018-05-23 17:35:11'),
	(10, 'sin pesas piernas', '2018-05-23 17:35:53', '2018-05-23 17:35:53'),
	(11, 'sin pesas todo el cuerpo', '2018-05-23 17:36:03', '2018-05-23 17:36:03'),
	(12, 'sin pesas tronco', '2018-05-23 17:36:37', '2018-05-23 17:36:37'),
	(13, 'Estiramientos', NULL, NULL);
/*!40000 ALTER TABLE `grupos` ENABLE KEYS */;

-- Volcando estructura para tabla gym.migrations
CREATE TABLE IF NOT EXISTS `migrations` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `migration` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `batch` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla gym.migrations: ~8 rows (aproximadamente)
/*!40000 ALTER TABLE `migrations` DISABLE KEYS */;
INSERT INTO `migrations` (`id`, `migration`, `batch`) VALUES
	(1, '2014_10_12_000000_create_users_table', 1),
	(2, '2014_10_12_100000_create_password_resets_table', 1),
	(3, '2018_05_29_194640_create_grupos_table', 1),
	(4, '2018_05_29_210341_create_modalidads_table', 1),
	(5, '2018_05_31_161725_create_ejercicios_table', 1),
	(6, '2018_06_02_123035_create_entrenos_table', 1),
	(7, '2018_06_02_123547_create_ejercicio_modalidad_table', 1),
	(8, '2018_06_16_135849_create_rutina_semanals_table', 1);
/*!40000 ALTER TABLE `migrations` ENABLE KEYS */;

-- Volcando estructura para tabla gym.modalidads
CREATE TABLE IF NOT EXISTS `modalidads` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `nombre` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla gym.modalidads: ~5 rows (aproximadamente)
/*!40000 ALTER TABLE `modalidads` DISABLE KEYS */;
INSERT INTO `modalidads` (`id`, `nombre`, `created_at`, `updated_at`) VALUES
	(1, 'definir', '2018-05-23 17:40:51', '2018-05-23 17:40:51'),
	(2, 'mantener', '2018-05-23 17:41:04', '2018-05-23 17:41:04'),
	(3, 'muscular', '2018-05-23 17:41:34', '2018-05-23 17:41:34'),
	(4, 'resistencia', '2018-05-23 17:41:45', '2018-05-23 17:41:46'),
	(5, 'estiramientos', '2018-05-23 17:41:58', '2018-05-23 17:41:58');
/*!40000 ALTER TABLE `modalidads` ENABLE KEYS */;

-- Volcando estructura para tabla gym.password_resets
CREATE TABLE IF NOT EXISTS `password_resets` (
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `token` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  KEY `password_resets_email_index` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla gym.password_resets: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `password_resets` DISABLE KEYS */;
/*!40000 ALTER TABLE `password_resets` ENABLE KEYS */;

-- Volcando estructura para tabla gym.rutina_semanals
CREATE TABLE IF NOT EXISTS `rutina_semanals` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `id_usuario` int(10) unsigned NOT NULL,
  `nombre` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `lunes` json NOT NULL,
  `martes` json NOT NULL,
  `miercoles` json NOT NULL,
  `jueves` json NOT NULL,
  `viernes` json NOT NULL,
  `sabado` json NOT NULL,
  `domingo` json NOT NULL,
  `repeticiones` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `serie` int(11) NOT NULL,
  `peso` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `nivel` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `rutina_semanals_id_usuario_foreign` (`id_usuario`),
  CONSTRAINT `rutina_semanals_id_usuario_foreign` FOREIGN KEY (`id_usuario`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla gym.rutina_semanals: ~0 rows (aproximadamente)
/*!40000 ALTER TABLE `rutina_semanals` DISABLE KEYS */;
/*!40000 ALTER TABLE `rutina_semanals` ENABLE KEYS */;

-- Volcando estructura para tabla gym.users
CREATE TABLE IF NOT EXISTS `users` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `apellido` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `dob` date NOT NULL,
  `sexo` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `remember_token` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_email_unique` (`email`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla gym.users: ~4 rows (aproximadamente)
/*!40000 ALTER TABLE `users` DISABLE KEYS */;
INSERT INTO `users` (`id`, `name`, `apellido`, `email`, `password`, `dob`, `sexo`, `remember_token`, `created_at`, `updated_at`) VALUES
	(1, 'raziel', 'Veizaga', 'razielveizaga@gmail.com', '$2y$10$t7J7MWgr.bjZCNBbavreKuu1QjpzS4q96JmBwIEVdpDIc/W7Jxixu', '1997-09-08', 'mujer', 'acjgL9xc4JzRVuPs2kRfTEUhBRcAmoncVJCC4S6Jo2neiZd6d3ng2bxzZyBx', '2018-06-17 10:57:14', '2018-06-17 10:57:14'),
	(2, 'karla', 'veizaga', 'jveizaga@gmail.com', '$2y$10$BDKaYiATqf/GXP7cgGjzvOxqTWIt8F35ytbDZ.UjTwVJMmSw8ZAwW', '1997-09-08', 'mujer', 'NFIoaCtrcbrvKroE9hIBD8D3md6A5sqJe2eeQQrogT7AhxdL7POdmmmzas7T', '2018-06-17 15:32:28', '2018-06-17 15:32:28'),
	(3, 'Gerson', 'Veizaga', 'gveizaga@gmail.com', '$2y$10$ufS13IrinHQTxabeKN6MHOBGZzgziSYag8sT0hLppjA4DzMuHyra.', '1995-09-08', 'hombre', 'fazuBAMTJPkTKTMsopH3Q4cmgsoIKWl3w1fTBd0AwJF288v4m4DBibRYRKZE', '2018-06-17 17:15:23', '2018-06-17 17:15:23'),
	(4, 'mario', 'segura', 'msegura@gmail.com', '$2y$10$.BGybWOwSnOemXZuUJd8nONnSvDEV3wqv3Fmzlr4tZ6c9lTWRAp5q', '1989-09-19', 'hombre', NULL, '2018-06-17 20:58:16', '2018-06-17 20:58:16'),
	(5, 'raziel', 'Veizaga', 'rveizaga@gmail.com', '$2y$10$86ZP7DsIca3Qsb/QW0wnmehwcT/croJZOSOKfC9FR6AzdgYxacSVK', '1997-09-08', 'mujer', 'bDWJvoTLjJ6i6MI1Ur6NdPSAFI3HghFfUFkVvM2apasXjeYdsiqiGh4oLplS', '2018-06-18 07:06:16', '2018-06-18 07:06:16');
/*!40000 ALTER TABLE `users` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
